// <auto-generated />
using System;
using AIJobHelper.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIJobHelper.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260515014012_Phase3_CoverLetter")]
    partial class Phase3_CoverLetter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AIJobHelper.Domain.Entities.AtsResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AiSummary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AtsChanges")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("JobDescriptionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("MatchedSkills")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("MissingSkills")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Suggestions")
                        .IsRequired()
                        .HasColumnType("json");

                    b.HasKey("Id");

                    b.HasIndex("JobDescriptionId");

                    b.HasIndex("ResumeId");

                    b.ToTable("AtsResults");
                });

            modelBuilder.Entity("AIJobHelper.Domain.Entities.CoverLetter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ConfigId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<Guid?>("JobDescriptionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PdfPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigId");

                    b.HasIndex("JobDescriptionId");

                    b.HasIndex("ResumeId");

                    b.ToTable("CoverLetters");
                });

            modelBuilder.Entity("AIJobHelper.Domain.Entities.CoverLetterConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FooterTemplate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HeaderTemplate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("CoverLetterConfigs");
                });

            modelBuilder.Entity("AIJobHelper.Domain.Entities.JobDescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ParsedContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("JobDescriptions");
                });

            modelBuilder.Entity("AIJobHelper.Domain.Entities.Resume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContentText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Resumes");
                });

            modelBuilder.Entity("AIJobHelper.Domain.Entities.ResumeAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Strengths")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Suggestions")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Weaknesses")
                        .IsRequired()
                        .HasColumnType("json");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId")
                        .IsUnique();

                    b.ToTable("ResumeAnalyses");
                });

            modelBuilder.Entity("AIJobHelper.Domain.Entities.AtsResult", b =>
                {
                    b.HasOne("AIJobHelper.Domain.Entities.JobDescription", "JobDescription")
                        .WithMany("AtsResults")
                        .HasForeignKey("JobDescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIJobHelper.Domain.Entities.Resume", "Resume")
                        .WithMany("AtsResults")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobDescription");

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("AIJobHelper.Domain.Entities.CoverLetter", b =>
                {
                    b.HasOne("AIJobHelper.Domain.Entities.CoverLetterConfig", "Config")
                        .WithMany("CoverLetters")
                        .HasForeignKey("ConfigId");

                    b.HasOne("AIJobHelper.Domain.Entities.JobDescription", "JobDescription")
                        .WithMany("CoverLetters")
                        .HasForeignKey("JobDescriptionId");

                    b.HasOne("AIJobHelper.Domain.Entities.Resume", "Resume")
                        .WithMany("CoverLetters")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Config");

                    b.Navigation("JobDescription");

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("AIJobHelper.Domain.Entities.ResumeAnalysis", b =>
                {
                    b.HasOne("AIJobHelper.Domain.Entities.Resume", "Resume")
                        .WithOne("Analysis")
                        .HasForeignKey("AIJobHelper.Domain.Entities.ResumeAnalysis", "ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("AIJobHelper.Domain.Entities.CoverLetterConfig", b =>
                {
                    b.Navigation("CoverLetters");
                });

            modelBuilder.Entity("AIJobHelper.Domain.Entities.JobDescription", b =>
                {
                    b.Navigation("AtsResults");

                    b.Navigation("CoverLetters");
                });

            modelBuilder.Entity("AIJobHelper.Domain.Entities.Resume", b =>
                {
                    b.Navigation("Analysis");

                    b.Navigation("AtsResults");

                    b.Navigation("CoverLetters");
                });
#pragma warning restore 612, 618
        }
    }
}
